/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProfessoresRouteImport } from './routes/professores'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IaRouteImport } from './routes/ia'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as IndexRouteImport } from './routes/index'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessoresRoute = ProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/ocr': typeof OcrRoute
  '/professores': typeof ProfessoresRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/ocr': typeof OcrRoute
  '/professores': typeof ProfessoresRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/ocr': typeof OcrRoute
  '/professores': typeof ProfessoresRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/avaliacoes'
    | '/configuracoes'
    | '/ia'
    | '/login'
    | '/ocr'
    | '/professores'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/avaliacoes'
    | '/configuracoes'
    | '/ia'
    | '/login'
    | '/ocr'
    | '/professores'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/avaliacoes'
    | '/configuracoes'
    | '/ia'
    | '/login'
    | '/ocr'
    | '/professores'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  IaRoute: typeof IaRoute
  LoginRoute: typeof LoginRoute
  OcrRoute: typeof OcrRoute
  ProfessoresRoute: typeof ProfessoresRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores': {
      id: '/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof ProfessoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  IaRoute: IaRoute,
  LoginRoute: LoginRoute,
  OcrRoute: OcrRoute,
  ProfessoresRoute: ProfessoresRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
